version: 2.1

orbs:
  python:
    executors:
      default:
        docker:
          - image: circleci/python:3.7
    commands:
      update_venv:
        steps:
          - restore_cache:
            key: dependency-cache-{{ checksum "setup.py" }}
          - run:
            name: install python dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              python setup.py install
          - save_cache:
            key: dependency-cache-{{ checksum "setup.py" }}
            paths:
              - "venv"
      run_tests:
        steps:
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              python setup.py test

    jobs:
      pytest:
        executor: default
        steps:
          - update_venv
          - run_tests

workflows:
    "Hello Workflow":
        jobs:
          - python/pytest
