orbs:
  python:
    executors:
      default:
        docker:
          - image: circleci/python:3.7
    commands:
      update_venv:
        steps:
           - restore_cache:
               key: dependency-cache-{{ checksum "setup.py" }}
           - run:
               name: install python dependencies
               command: |
                 python3 -m venv venv
                 . venv/bin/activate
                 python setup.py install
           - save_cache:
               key: dependency-cache-{{ checksum "setup.py" }}
               paths:
                 - "venv"
      run_tests:
        steps:
          - run:
              command: |
                . venv/bin/activate
                python setup.py test
    jobs:
      pytest:
        executor: default
        steps:
          - checkout
          - update_venv
          - run_tests

version: 2.1
workflows:
  main:
    jobs:
      - python/pytest
