version: 2.1

orbs:
  python:
    executors:
      default:
        docker:
          - image: circleci/python:3.7
    commands:
      dospecialthings:
        steps:
          - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: default
        steps:
          - dospecialthings

workflows:
    "Hello Workflow":
        jobs:
          - python/myjob
